"""Deterministic MAGUS input/slurm renderers (Sprint 4, sections 24-28).

The domain models in ``models.py`` are mapped here onto the MAGUS 2.1.0
YAML keys verified from the installed official examples
(``~/magus/examples.zip`` on SCNet):

* generate: 01--1-B12/input.yaml, 01--2-NH4NO3/input.yaml
* search:   03--1-Al-fix-EMT/input.yaml, 03--2-Al-fix-VASP/input.yaml
* cluster:  05--1-LJ26/input.yaml
* surface:  06--1-C_2x1_100/input.yaml

The LLM never supplies raw YAML; every key below is either a verified
MAGUS key or a documented PhotoMatAgent domain field mapped by this module.
"""

from __future__ import annotations

import hashlib
import shlex
from typing import Any

from photomatagent.scientific.applications.magus.models import (
    MagusGenerateRequest,
    MagusSearchRequest,
)
from photomatagent.scientific.remote.scheduler import render_slurm_script
from photomatagent.scientific.remote.scnet import validate_remote_path

# Default VASP INCAR written into ``inputFold/VASP/INCAR`` for MAGUS VASP
# searches. Field provenance: installed example
# ``02--1-C8-VASP/inputFold/VASP/INCAR`` (MAGUS 2.1.0) -- MAGUS's
# ``RelaxVasp`` overrides LCHARG/LWAVE and pressure at runtime, so the
# values below are a minimal, conservative baseline for tiny acceptance
# runs; production searches should tune per system.
MAGUS_VASP_INCAR = """SYSTEM = MAGUS
PREC = Normal
EDIFF = 1e-3
IBRION = 2
ISIF = 3
NSW = 40
ISMEAR = 0
SIGMA = 0.050
POTIM = 0.250
ISTART = 0
LCHARG = FALSE
LWAVE = FALSE
EDIFFG = 1e-2
KSPACING = 0.314
NCORE = 1
"""


def _yaml_quote(value: Any) -> str:
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def _render_structure_block(request: MagusGenerateRequest | MagusSearchRequest) -> list[str]:
    composition = request.composition
    lines = [
        f"formulaType: {composition.formula_type}",
        f"structureType: {request.structure_type}",
        "symbols: " + "[" + ", ".join(_yaml_quote(s) for s in composition.symbols) + "]",
        "formula: " + "[" + ", ".join(str(f) for f in composition.formula) + "]",
    ]
    if request.min_atoms is not None:
        lines.append(f"min_n_atoms: {request.min_atoms}")
    if request.max_atoms is not None:
        lines.append(f"max_n_atoms: {request.max_atoms}")
    lines.append(
        "spacegroup: "
        + "[" + ", ".join(_yaml_quote(s) for s in request.spacegroup) + "]"
    )
    return lines


def render_generate_input(request: MagusGenerateRequest) -> str:
    """Render ``input.yaml`` for ``magus generate`` (no calculator)."""
    lines: list[str] = [
        "# Generated by PhotoMatAgent (deterministic renderer; MAGUS 2.1.0 keys).",
    ]
    lines.extend(_render_structure_block(request))
    lines.append(f"d_ratio: {request.d_ratio:g}")
    lines.append(f"volume_ratio: {request.volume_ratio:g}")
    return "\n".join(lines) + "\n"


def _render_surface_block(request: MagusSearchRequest) -> list[str]:
    slab = request.slab
    if slab is None:
        return []
    lines = [
        f"vacuum_thickness: {slab.vacuum_thickness:g}",
        f"spg_type: {_yaml_quote(slab.spg_type)}",
        "rcs_x: " + "[" + ", ".join(str(v) for v in slab.rcs_x) + "]",
        "rcs_y: " + "[" + ", ".join(str(v) for v in slab.rcs_y) + "]",
        "d_ratio: 0.6",
        "randRatio: 0.3",
        "randwalk_ratio: 1",
        "add_sym: False",
        "modification:",
        "  clean: {}",
        "Comparator:",
        "  comparator_list: ['naive']",
        "slabinfo:",
        f"  bulk_file: {_yaml_quote(slab.bulk_file)}",
        f"  cutslices: {slab.cutslices}",
        f"  bulk_layernum: {slab.bulk_layernum}",
        f"  buffer_layernum: {slab.buffer_layernum}",
        f"  rcs_layernum: {slab.rcs_layernum}",
        "  direction: " + "[" + ", ".join(str(v) for v in slab.direction) + "]",
    ]
    return lines


def render_search_input(request: MagusSearchRequest) -> str:
    """Render ``input.yaml`` for ``magus search`` with a calculator."""
    composition = request.composition
    lines: list[str] = [
        "# Generated by PhotoMatAgent (deterministic renderer; MAGUS 2.1.0 keys).",
    ]
    lines.extend(_render_structure_block(request))
    lines.append(f"pressure: {request.pressure_gpa:g}")
    lines.append(f"initSize: {request.init_size}")
    lines.append(f"popSize: {request.population_size}")
    lines.append(f"numGen: {request.generations}")
    lines.append(f"saveGood: {request.save_good}")
    lines.append(f"d_ratio: {request.d_ratio:g}")
    lines.append(f"volume_ratio: {request.volume_ratio:g}")
    lines.append(f"rand_ratio: {request.rand_ratio:g}")
    lines.append(f"add_sym: {_yaml_quote(request.add_sym)}")
    lines.extend(_render_surface_block(request))
    calculator_block: dict[str, Any] = {
        "calculator": request.calculator,
        "mode": request.execution_mode,
        "jobPrefix": ["VASP"],
    }
    if request.calculator == "vasp":
        calculator_block["xc"] = "PBE"
        setups = [req.setup for req in request.pseudopotentials] or [""] * len(
            composition.symbols
        )
        if len(setups) != len(composition.symbols):
            setups = [""] * len(composition.symbols)
        calculator_block["ppLabel"] = setups
    if request.calculator in {"emt", "lj"}:
        calculator_block.update({"eps": 0.05, "maxStep": 30, "maxMove": 0.1})
    lines.append("MainCalculator:")
    for key, value in calculator_block.items():
        if isinstance(value, list):
            rendered = "[" + ", ".join(_yaml_quote(v) for v in value) + "]"
        else:
            rendered = _yaml_quote(value)
        lines.append(f"  {key}: {rendered}")
    return "\n".join(lines) + "\n"


def magus_arguments(
    operation: str, request: MagusGenerateRequest | MagusSearchRequest
) -> list[str]:
    """Deterministic CLI arguments for the installed MAGUS 2.1.0 CLI.

    Verified against ``magus generate -h`` / ``magus search -h`` on the
    installed version:
    ``generate -i input.yaml -o gen.traj -n N`` and ``search -i input.yaml``.
    """
    if operation == "generate":
        assert isinstance(request, MagusGenerateRequest)
        return [
            "generate",
            "-i",
            "input.yaml",
            "-o",
            "gen.traj",
            "-n",
            str(request.number),
        ]
    if operation == "search":
        assert isinstance(request, MagusSearchRequest)
        return ["search", "-i", "input.yaml"]
    raise ValueError(f"unknown MAGUS operation {operation!r}")


def render_magus_slurm(
    *,
    job_name: str,
    executable: str,
    args: list[str],
    resource: Any,
    magus_root: str = "",
    env_script: str = "",
    vasp_script: str = "",
    vasp_pp_path: str = "",
    job_system: str = "SLURM",
) -> str:
    """Render the MAGUS Slurm script (launcher empty: MAGUS is the workflow
    controller running inside the allocation; never ``srun magus``)."""
    if not executable:
        raise ValueError("MAGUS executable is required")
    env_vars: dict[str, str] = {}
    if job_system:
        env_vars["JOB_SYSTEM"] = job_system
    if magus_root:
        validate_remote_path(magus_root, allow_tilde=True)
        env_vars["PATH"] = f"{magus_root}/bin:$PATH"
    if vasp_pp_path:
        validate_remote_path(vasp_pp_path, allow_tilde=True)
        env_vars["VASP_PP_PATH"] = vasp_pp_path
    preamble_parts: list[str] = []
    scripts = [script for script in (vasp_script, env_script) if script]
    for script in scripts:
        validate_remote_path(script, allow_tilde=False)
        preamble_parts.append(
            "set +e\n" + f"source {shlex.quote(script)}\n" + "set -e"
        )
    preamble = "\n".join(preamble_parts)
    return render_slurm_script(
        job_name=job_name,
        resource=resource,
        executable=executable,
        executable_args=args,
        env_vars=env_vars,
        preamble=preamble,
        launcher="",
    )


def manifest_input_hash(input_yaml: str) -> str:
    return hashlib.sha256(input_yaml.encode("utf-8")).hexdigest()[:16]
