"""Pure data contracts for mechanism hypotheses and discovery constraints."""

from __future__ import annotations

from datetime import datetime
from math import gcd
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from photomatagent.scientific.capabilities.generation.lineage import CandidateLineage

DesignOperation = Literal[
    "isovalent_substitution",
    "ordering",
    "distortion",
    "prototype_transfer",
    "synthesis_constrained",
    "other",
]
BasisRelation = Literal["analogue", "supports", "contradicts"]
EffectDirection = Literal["increase", "decrease", "change", "unknown"]

NonEmptyId = Annotated[str, Field(min_length=1)]
BoundedText1000 = Annotated[str, Field(min_length=1, max_length=1_000)]
BoundedText1500 = Annotated[str, Field(min_length=1, max_length=1_500)]


class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


class BasisReference(_StrictModel):
    """A traceable evidence reference used as a proposal basis."""

    evidence_id: NonEmptyId
    relation: BasisRelation
    anchor: str = ""


class ExpectedEffect(_StrictModel):
    """A qualitative, unvalidated property effect expected by the model."""

    property: Annotated[str, Field(min_length=1)]
    direction: EffectDirection
    rationale: Annotated[str, Field(min_length=1)]


class HypothesisProposal(_StrictModel):
    """The complete set of hypothesis fields that a model may submit."""

    request_id: Annotated[str, Field(min_length=1, max_length=128)]
    formula: Annotated[str, Field(min_length=1, max_length=256)]
    statement: Annotated[str, Field(min_length=1, max_length=2_000)]
    design_operation: DesignOperation
    parent_hypothesis_ids: list[NonEmptyId] = Field(default_factory=list, max_length=8)
    basis: list[BasisReference] = Field(default_factory=list, max_length=16)
    assumptions: list[BoundedText1000] = Field(default_factory=list, max_length=12)
    expected_effects: list[ExpectedEffect] = Field(default_factory=list, max_length=12)
    counter_hypotheses: list[BoundedText1000] = Field(default_factory=list, max_length=8)
    validation_questions: list[BoundedText1000] = Field(min_length=1, max_length=12)
    synthesis_notes: list[BoundedText1500] = Field(default_factory=list, max_length=8)

    @field_validator("formula")
    @classmethod
    def formula_has_no_unexpanded_variable(cls, formula: str) -> str:
        if "x" in formula:
            raise ValueError("formula must not contain an unexpanded x variable")
        return formula


class HypothesisRegistration(_StrictModel):
    """Pure update command requesting registration of one proposal."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, frozen=True)

    proposal: HypothesisProposal


class HypothesisOrigin(_StrictModel):
    """Runtime-owned provenance for a registered hypothesis."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, frozen=True)

    tool_name: str
    tool_call_id: str
    session_id: str
    run_id: str
    provider: str
    model: str


class ScientificHypothesis(_StrictModel):
    """Immutable runtime record for one registered scientific hypothesis."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, frozen=True)

    id: NonEmptyId
    candidate_id: NonEmptyId
    proposal: HypothesisProposal
    normalized_composition: tuple[tuple[str, int], ...]
    request_payload_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    lineage: CandidateLineage
    origin: HypothesisOrigin
    created_at: datetime

    @model_validator(mode="after")
    def normalized_composition_is_canonical(self) -> "ScientificHypothesis":
        if self.lineage.generated_by != "mechanism_reasoning":
            raise ValueError("hypothesis lineage must be generated by mechanism_reasoning")
        if self.lineage.validation_status != "UNVALIDATED_HYPOTHESIS":
            raise ValueError("hypothesis lineage must remain UNVALIDATED_HYPOTHESIS")
        composition = self.normalized_composition
        if not composition or len(composition) > 16:
            raise ValueError("normalized_composition must contain 1 to 16 elements")
        symbols = [symbol for symbol, _ in composition]
        if any(not symbol for symbol in symbols) or symbols != sorted(symbols):
            raise ValueError("normalized_composition elements must be non-empty and sorted")
        amounts = [amount for _, amount in composition]
        if any(amount <= 0 for amount in amounts):
            raise ValueError("normalized_composition amounts must be positive integers")
        divisor = amounts[0]
        for amount in amounts[1:]:
            divisor = gcd(divisor, amount)
        if divisor != 1:
            raise ValueError("normalized_composition amounts must be reduced")
        return self


class DiscoveryConstraints(_StrictModel):
    """Optional mechanism-discovery constraints supplied by the caller."""

    required_elements: list[str] = Field(default_factory=list)
    forbidden_elements: list[str] = Field(default_factory=list)
    allow_isovalent_alloy: bool | None = None
    allow_donor_acceptor_doping: bool | None = None
