#!/usr/bin/env bash
# Resumable WSL driver for the two local literature-ingestion stages.
#
# The driver deliberately contains no provider or database logic.  It selects
# source paths and durable run IDs, then delegates all work to the project's
# Typer CLI through the repository's uv environment.

set -euo pipefail

DEFAULT_WORKSPACE="/home/shiqiany/AIagent"
DEFAULT_PDF_DIRECTORY="Photoelectric detection/dataset/paper/pdf"
DEFAULT_ABSTRACT_DATABASE="Photoelectric detection/dataset/paper/abstract/abstracts.sqlite3"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

WORKSPACE="${PHOTOMATAGENT_RAG_WORKSPACE:-$DEFAULT_WORKSPACE}"
PDF_DIRECTORY="${PHOTOMATAGENT_RAG_PDF_DIRECTORY:-$DEFAULT_PDF_DIRECTORY}"
ABSTRACT_DATABASE="${PHOTOMATAGENT_RAG_ABSTRACT_DATABASE:-$DEFAULT_ABSTRACT_DATABASE}"
RUN_STATE_OVERRIDE="${PHOTOMATAGENT_RAG_IMPORT_STATE_DIR:-}"

STAGE=""
STOP_AFTER=""
RESUME=false
DRY_RUN=false
YES=false
SUPERSEDE_RUN_ID=""

usage() {
  cat <<EOF
Usage: scripts/import_literature_qdrant.sh <pdf|abstracts|status|activate> [options]

Stages:
  pdf         Import local PDF full-text passages.
  abstracts   Import rows from the local abstracts SQLite database.
  status      Show Qdrant, alias, and both saved stage-run states.
  activate    Validate both completed stages and atomically activate aliases.

Options:
  --workspace PATH          Workspace passed to PhotomatAgent
  --pdf-directory PATH      Workspace-relative PDF directory (pdf stage)
  --database PATH            Workspace-relative abstracts SQLite path
  --run-state-dir PATH       Override local run-state directory
  --stop-after N             Pause after at most N source records (index stages)
  --resume                  Reuse the saved stage run ID (index stages)
  --supersede-run-id ID      Abstracts: explicitly replace a previous run after
                             a changed SQLite source
  --dry-run                 Print shell-escaped argv without starting uv
  --yes                     Forward explicit provider/activation confirmation
  -h, --help                Show this help

Defaults:
  workspace: $DEFAULT_WORKSPACE
  PDF directory: $DEFAULT_PDF_DIRECTORY
  abstracts database: $DEFAULT_ABSTRACT_DATABASE
  run state: <repository>/user_output/rag-import/run-state/{pdf,abstracts}.run_id
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 2
}

require_option_value() {
  local option="$1"
  if [[ "$#" -lt 2 || -z "${2:-}" ]]; then
    die "${option} requires a value"
  fi
}

validate_stop_after() {
  local value="$1"
  [[ "$value" =~ ^[1-9][0-9]*$ ]] || die "--stop-after must be a positive integer"
}

new_run_id() {
  if [[ -r /proc/sys/kernel/random/uuid ]]; then
    local generated
    generated="$(< /proc/sys/kernel/random/uuid)"
    if [[ -n "$generated" ]]; then
      printf '%s\n' "$generated"
      return 0
    fi
  fi
  if command -v uuidgen >/dev/null 2>&1; then
    uuidgen
    return 0
  fi
  # The CLI accepts an opaque non-empty run ID.  This fallback is only for
  # minimal WSL images without /proc UUID support or uuidgen.
  printf 'rag-%s-%s\n' "$(date +%s%N)" "$RANDOM"
}

trim_run_id() {
  local value="$1"
  value="${value//$'\r'/}"
  # IDs generated by this script contain no whitespace.  Trimming the edges
  # keeps manually inspected state files usable without changing an ID's
  # interior characters.
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

load_run_id() {
  local state_file="$1"
  local stage_name="$2"
  if [[ ! -f "$state_file" ]]; then
    die "no saved ${stage_name} run ID at ${state_file}; run ${stage_name} without --resume first"
  fi
  local value=""
  IFS= read -r value < "$state_file" || true
  value="$(trim_run_id "$value")"
  [[ -n "$value" ]] || die "saved ${stage_name} run ID is empty: ${state_file}"
  printf '%s\n' "$value"
}

save_run_id() {
  local state_file="$1"
  local value="$2"
  local state_dir
  state_dir="$(dirname -- "$state_file")"
  mkdir -p -- "$state_dir"
  local temporary="${state_file}.tmp.$$"
  printf '%s\n' "$value" > "$temporary"
  mv -f -- "$temporary" "$state_file"
}

archive_run_id() {
  local stage_name="$1"
  local value="$2"
  [[ -n "$value" ]] || return 0
  local archive_dir="${RUN_STATE_DIR}/archive"
  mkdir -p -- "$archive_dir"
  # Keep the original ID in the file contents while sanitising only the
  # operator-visible filename.  The counter handles two invocations in the
  # same second without overwriting an earlier audit copy.
  local safe_value="${value//[^A-Za-z0-9._-]/_}"
  local timestamp
  timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
  local archive_file="${archive_dir}/${stage_name}.${safe_value}.${timestamp}.$$"
  local suffix=0
  while [[ -e "$archive_file" ]]; do
    suffix=$((suffix + 1))
    archive_file="${archive_dir}/${stage_name}.${safe_value}.${timestamp}.$$.${suffix}"
  done
  save_run_id "$archive_file" "$value"
}

print_dry_run() {
  printf 'dry-run argv:'
  printf ' %q' "$@"
  printf '\n'
  # Keep resolved paths visible for operators while the preceding line stays
  # a directly pasteable shell-escaped argv.  This also makes paths with
  # spaces unambiguous in logs and smoke tests.
  printf 'dry-run workspace: %s\n' "$WORKSPACE"
  printf 'dry-run PDF directory: %s\n' "$PDF_DIRECTORY"
  printf 'dry-run abstracts database: %s\n' "$ABSTRACT_DATABASE"
}

run_command() {
  local -a command=("$@")
  if [[ "$DRY_RUN" == true ]]; then
    print_dry_run "${command[@]}"
    return 0
  fi
  "${command[@]}"
}

if [[ "$#" -eq 0 ]]; then
  usage
  exit 2
fi

case "$1" in
  -h|--help)
    usage
    exit 0
    ;;
  pdf|abstracts|status|activate)
    STAGE="$1"
    shift
    ;;
  *)
    die "stage must be one of pdf|abstracts|status|activate (use --help for details)"
    ;;
esac

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --workspace)
      require_option_value "$@"
      WORKSPACE="$2"
      shift 2
      ;;
    --workspace=*)
      WORKSPACE="${1#*=}"
      [[ -n "$WORKSPACE" ]] || die "--workspace requires a value"
      shift
      ;;
    --pdf-directory|--pdf-dir)
      require_option_value "$@"
      PDF_DIRECTORY="$2"
      shift 2
      ;;
    --pdf-directory=*|--pdf-dir=*)
      PDF_DIRECTORY="${1#*=}"
      [[ -n "$PDF_DIRECTORY" ]] || die "$1 requires a value"
      shift
      ;;
    --database|--abstract-database|--abstract-db)
      require_option_value "$@"
      ABSTRACT_DATABASE="$2"
      shift 2
      ;;
    --database=*|--abstract-database=*|--abstract-db=*)
      ABSTRACT_DATABASE="${1#*=}"
      [[ -n "$ABSTRACT_DATABASE" ]] || die "$1 requires a value"
      shift
      ;;
    --run-state-dir)
      require_option_value "$@"
      RUN_STATE_OVERRIDE="$2"
      shift 2
      ;;
    --run-state-dir=*)
      RUN_STATE_OVERRIDE="${1#*=}"
      [[ -n "$RUN_STATE_OVERRIDE" ]] || die "--run-state-dir requires a value"
      shift
      ;;
    --stop-after)
      require_option_value "$@"
      validate_stop_after "$2"
      STOP_AFTER="$2"
      shift 2
      ;;
    --stop-after=*)
      STOP_AFTER="${1#*=}"
      validate_stop_after "$STOP_AFTER"
      shift
      ;;
    --resume)
      RESUME=true
      shift
      ;;
    --supersede-run-id)
      require_option_value "$@"
      SUPERSEDE_RUN_ID="$(trim_run_id "$2")"
      [[ -n "$SUPERSEDE_RUN_ID" ]] || die "--supersede-run-id requires a value"
      shift 2
      ;;
    --supersede-run-id=*)
      SUPERSEDE_RUN_ID="$(trim_run_id "${1#*=}")"
      [[ -n "$SUPERSEDE_RUN_ID" ]] || die "--supersede-run-id requires a value"
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --yes)
      YES=true
      shift
      ;;
    --)
      shift
      [[ "$#" -eq 0 ]] || die "unexpected positional argument: $1"
      ;;
    *)
      die "unknown option or argument: $1"
      ;;
  esac
done

if [[ "$STAGE" == "status" || "$STAGE" == "activate" ]]; then
  [[ -z "$STOP_AFTER" ]] || die "--stop-after is only valid for pdf or abstracts"
  [[ "$RESUME" == false ]] || die "--resume is only valid for pdf or abstracts"
  [[ -z "$SUPERSEDE_RUN_ID" ]] || die "--supersede-run-id is only valid for abstracts"
fi

if [[ "$STAGE" == "pdf" ]]; then
  [[ -z "$SUPERSEDE_RUN_ID" ]] || die "--supersede-run-id is only valid for abstracts"
fi
if [[ "$RESUME" == true ]]; then
  [[ -z "$SUPERSEDE_RUN_ID" ]] || die "--resume cannot be combined with --supersede-run-id"
fi

if [[ -n "$RUN_STATE_OVERRIDE" ]]; then
  RUN_STATE_DIR="$RUN_STATE_OVERRIDE"
else
  RUN_STATE_DIR="${REPOSITORY_ROOT}/user_output/rag-import/run-state"
fi
PDF_STATE_FILE="${RUN_STATE_DIR}/pdf.run_id"
ABSTRACTS_STATE_FILE="${RUN_STATE_DIR}/abstracts.run_id"

if [[ "$STAGE" == "pdf" || "$STAGE" == "abstracts" ]]; then
  STATE_FILE="$PDF_STATE_FILE"
  STAGE_LABEL="pdf"
  if [[ "$STAGE" == "abstracts" ]]; then
    STATE_FILE="$ABSTRACTS_STATE_FILE"
    STAGE_LABEL="abstracts"
  fi

  if [[ "$RESUME" == true ]]; then
    RUN_ID="$(load_run_id "$STATE_FILE" "$STAGE_LABEL")"
  else
    PREVIOUS_RUN_ID=""
    if [[ -f "$STATE_FILE" ]]; then
      IFS= read -r PREVIOUS_RUN_ID < "$STATE_FILE" || true
      PREVIOUS_RUN_ID="$(trim_run_id "$PREVIOUS_RUN_ID")"
    fi
    if [[ "$STAGE" == "abstracts" && -z "$SUPERSEDE_RUN_ID" ]]; then
      # A fresh abstract invocation following a saved run is a source
      # replacement by default.  Forwarding the old ID makes the lifecycle
      # explicit at the CLI while preserving the driver's audit trail.
      SUPERSEDE_RUN_ID="$PREVIOUS_RUN_ID"
    fi
    RUN_ID="$(new_run_id)"
    if [[ "$DRY_RUN" == false ]]; then
      # This is intentionally before invoking uv: an interrupted process can
      # always be resumed with the exact ID sent to the CLI.
      if [[ -n "$PREVIOUS_RUN_ID" ]]; then
        archive_run_id "$STAGE_LABEL" "$PREVIOUS_RUN_ID"
      fi
      save_run_id "$STATE_FILE" "$RUN_ID"
    fi
  fi

  COMMAND=(uv run photomatagent rag)
  if [[ "$STAGE" == "pdf" ]]; then
    COMMAND+=(index --workspace "$WORKSPACE" --directory "$PDF_DIRECTORY")
  else
    COMMAND+=(index-abstracts --workspace "$WORKSPACE" --database "$ABSTRACT_DATABASE")
  fi
  COMMAND+=(--run-id "$RUN_ID")
  if [[ "$RESUME" == true ]]; then
    COMMAND+=(--resume)
  fi
  if [[ "$STAGE" == "abstracts" && -n "$SUPERSEDE_RUN_ID" ]]; then
    COMMAND+=(--supersede-run-id "$SUPERSEDE_RUN_ID")
  fi
  if [[ -n "$STOP_AFTER" ]]; then
    COMMAND+=(--stop-after "$STOP_AFTER")
  fi
  if [[ "$YES" == true ]]; then
    COMMAND+=(--yes)
  fi
  cd -- "$REPOSITORY_ROOT"
  run_command "${COMMAND[@]}"
  exit $?
fi

# Status and activation are read/validate operations owned by the CLI.  Both
# stage IDs are loaded from local state; activation refuses to run if either is
# absent so the CLI always receives two explicit, bounded stage requirements.
PDF_RUN_ID=""
ABSTRACT_RUN_ID=""
if [[ -f "$PDF_STATE_FILE" ]]; then
  IFS= read -r PDF_RUN_ID < "$PDF_STATE_FILE" || true
  PDF_RUN_ID="$(trim_run_id "$PDF_RUN_ID")"
fi
if [[ -f "$ABSTRACTS_STATE_FILE" ]]; then
  IFS= read -r ABSTRACT_RUN_ID < "$ABSTRACTS_STATE_FILE" || true
  ABSTRACT_RUN_ID="$(trim_run_id "$ABSTRACT_RUN_ID")"
fi

cd -- "$REPOSITORY_ROOT"
if [[ "$STAGE" == "status" ]]; then
  COMMAND=(
    uv run photomatagent rag status
    --workspace "$WORKSPACE"
    --pdf-run-id "$PDF_RUN_ID"
    --abstract-run-id "$ABSTRACT_RUN_ID"
  )
  run_command "${COMMAND[@]}"
  exit $?
fi

[[ -n "$PDF_RUN_ID" ]] || die "activate requires a saved PDF run ID at ${PDF_STATE_FILE}"
[[ -n "$ABSTRACT_RUN_ID" ]] || die "activate requires a saved abstracts run ID at ${ABSTRACTS_STATE_FILE}"
COMMAND=(
  uv run photomatagent rag activate
  --workspace "$WORKSPACE"
  --require-stage pdf
  --require-stage abstracts
  --pdf-run-id "$PDF_RUN_ID"
  --abstract-run-id "$ABSTRACT_RUN_ID"
)
if [[ "$YES" == true ]]; then
  COMMAND+=(--yes)
fi
run_command "${COMMAND[@]}"
