"""Canonical JSON encoding and SHA-256 fingerprints for unified VASP workflows.

Fingerprints are generated by these factory functions only; callers never
supply them in public request models. Resource changes must NOT alter the
scientific fingerprint, but they do participate in the execution fingerprint.
"""

from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, cast

from pydantic import BaseModel

from photomatagent.scientific.applications.vasp.unified.models import (
    MolecularScientificSpec,
    PeriodicScientificSpec,
    ScientificSpec,
    StudyScientificSpec,
    UnifiedStage,
    UnifiedVaspManifest,
    UnifiedVaspRequest,
)
from photomatagent.scientific.remote.models import ResourceRequest


def _normalize(value: Any) -> Any:
    """Recursively normalize a Python value for canonical JSON hashing."""
    if isinstance(value, BaseModel):
        return _normalize(value.model_dump(mode="json"))
    if isinstance(value, Path):
        return _normalize(os.path.normpath(str(value)).replace("\\", "/"))
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, bytes):
        return value.hex()
    if isinstance(value, dict):
        return {str(key): _normalize(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_normalize(item) for item in value]
    if isinstance(value, set):
        return sorted((_normalize(item) for item in value), key=lambda item: json.dumps(item, sort_keys=True))
    if hasattr(value, "value"):
        return _normalize(value.value)
    return value


def canonical_json(value: Any) -> str:
    """Return deterministic, dictionary-order-independent JSON text."""
    return json.dumps(
        _normalize(value),
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _structure_marker(path: str | Path | None) -> dict[str, str] | None:
    """Hash a structure reference's normalized path and file content.

    If the file is unavailable, the normalized path alone is recorded so
    equivalent relative spellings still produce the same marker while a real
    path or content change is still detected.
    """
    if path is None or path == "":
        return None
    normalized = os.path.normpath(str(path)).replace("\\", "/")
    try:
        digest = hashlib.sha256(Path(path).read_bytes()).hexdigest()
    except OSError:
        digest = ""
    return {"path": normalized, "sha256": digest}


def _scientific_spec_payload(spec: ScientificSpec) -> dict[str, Any]:
    """Return the canonical scientific payload for one typed spec."""
    payload = spec.model_dump(mode="json")
    kind = spec.kind
    if kind == "periodic":
        periodic = cast(PeriodicScientificSpec, spec)
        marker = _structure_marker(periodic.structure_path)
        if marker is not None:
            payload["structure"] = marker
        payload.pop("structure_path", None)
    elif kind == "molecular":
        molecular = cast(MolecularScientificSpec, spec)
        marker = _structure_marker(molecular.workflow.molecule.structure_path)
        if marker is not None:
            payload["molecular_structure"] = marker
        payload.get("workflow", {}).get("molecule", {}).pop("structure_path", None)
    elif kind == "study":
        study = cast(StudyScientificSpec, spec)
        markers = [
            marker
            for system in study.request.systems
            if (marker := _structure_marker(system.structure_path)) is not None
        ]
        if markers:
            payload["study_structures"] = markers
        for system in payload.get("request", {}).get("systems", []):
            system.pop("structure_path", None)
    return payload


def _stage_topology(stages: Iterable[UnifiedStage] | None) -> list[dict[str, Any]]:
    """Only stable science-relevant stage topology enters scientific hash."""
    if not stages:
        return []
    return [
        {
            "name": stage.name,
            "depends_on": sorted(stage.depends_on),
        }
        for stage in stages
    ]


def scientific_fingerprint(
    spec_or_manifest: ScientificSpec | UnifiedVaspManifest | UnifiedVaspRequest,
    stages: Iterable[UnifiedStage] | None = None,
) -> str:
    """Compute the canonical scientific intent fingerprint.

    Resource fields, workflow state, request IDs, and event logs are
    intentionally excluded.
    """
    if isinstance(spec_or_manifest, UnifiedVaspManifest):
        spec = spec_or_manifest.scientific_spec
        if stages is None:
            stages = spec_or_manifest.stages
    elif isinstance(spec_or_manifest, UnifiedVaspRequest):
        spec = spec_or_manifest.scientific_spec
        if stages is None:
            stages = []
    else:
        spec = spec_or_manifest
    payload = {
        "scientific_spec": _scientific_spec_payload(spec),
        "stages": _stage_topology(stages),
    }
    return _sha256(canonical_json(payload))


def execution_fingerprint(
    scientific: str | ScientificSpec | UnifiedVaspManifest | UnifiedVaspRequest,
    resource: ResourceRequest | None = None,
    stage: UnifiedStage | str | None = None,
    attempt_inputs: dict[str, Any] | None = None,
) -> str:
    """Compute an execution fingerprint from science plus effective resources.

    ``attempt_inputs`` may include restart-specific artifacts (for example a
    validated CONTCAR hash) without changing the scientific fingerprint.
    """
    if isinstance(scientific, str):
        scientific_hash = scientific
    else:
        scientific_hash = scientific_fingerprint(scientific)
    stage_name = stage.name if isinstance(stage, UnifiedStage) else stage
    payload: dict[str, Any] = {
        "scientific_fingerprint": scientific_hash,
        "resource": resource.model_dump(mode="json") if resource is not None else None,
        "stage": stage_name,
        "attempt_inputs": attempt_inputs or None,
    }
    return _sha256(canonical_json(payload))
