"""Molecular VASP internal adapter over the existing domain facade."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

from photomatagent.scientific.applications.vasp.molecular.models import (
    StageName,
    WorkflowSpec,
)
from photomatagent.scientific.applications.vasp.molecular.binding import (
    BindingReference,
)
from photomatagent.scientific.applications.vasp.molecular.runtime import (
    MolecularVaspRuntime,
)
from photomatagent.scientific.applications.vasp.molecular.tools import (
    MolecularVaspTools,
)
from photomatagent.scientific.applications.vasp.unified.executors import (
    CollectionResult,
    OperationResult,
    PreflightResult,
    RecoveryResult,
    ReportResult,
    StatusResult,
    SubmissionResult,
)
from photomatagent.scientific.remote.lifecycle import derive_request_id
from photomatagent.scientific.applications.vasp.unified.fingerprints import execution_fingerprint
from photomatagent.scientific.applications.vasp.unified.models import (
    MolecularScientificSpec,
    ReportRequest,
    UnifiedStage,
    UnifiedVaspManifest,
)
from photomatagent.scientific.applications.vasp.unified.repository import (
    resolve_workspace_relative_path,
)
from photomatagent.scientific.capabilities.contracts import ScientificEvidence
from photomatagent.scientific.remote.models import ResourceRequest
from photomatagent.workspace import Workspace


class MolecularVaspExecutorAdapter:
    """Task 8 adapter: existing molecular science behind the unified contract."""

    def __init__(
        self,
        runtime: MolecularVaspRuntime,
        workflow_dir: str | Path | None = None,
        *,
        workspace: Workspace | None = None,
    ) -> None:
        self.runtime = runtime
        self.workspace = workspace or getattr(runtime, "workspace", None)
        if self.workspace is None and runtime.workflow_dir is not None:
            self.workspace = Workspace(Path(runtime.workflow_dir).parent)
        if self.workspace is None:
            raise ValueError("molecular adapter requires an authoritative Workspace")
        configured_root = (
            Path(workflow_dir).expanduser()
            if workflow_dir is not None
            else (
                runtime.workflow_dir
                if runtime.workflow_dir is not None
                else Path.cwd() / "output" / "vasp_molecule_unified"
            )
        )
        self._assert_safe_root(configured_root)
        if self.workspace is not None:
            if not configured_root.resolve().is_relative_to(self.workspace.root):
                raise ValueError("molecular workflow root is outside the workspace")
        self.workflow_dir = configured_root.resolve()
        self.workflow_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _assert_safe_root(root: Path) -> None:
        cursor = Path(root.anchor)
        for part in root.parts[1:]:
            cursor /= part
            if cursor.is_symlink():
                raise ValueError(f"molecular workflow root contains symlink: {cursor}")

    def workflow_dir_for(self, manifest: UnifiedVaspManifest) -> Path:
        """Return the stable, per-manifest workspace directory.

        A single adapter may serve many manifests (notably study children),
        so sharing ``runtime.workflow_dir`` would make task state and inputs
        overwrite one another.  IDs are generated by the manifest repository;
        reject path-like values here as an additional containment boundary.
        """
        workflow_id = manifest.workflow_id
        candidate_id = Path(workflow_id)
        if (
            candidate_id.is_absolute()
            or candidate_id.name != workflow_id
            or ".." in candidate_id.parts
        ):
            raise ValueError(f"invalid workflow id for molecular directory: {workflow_id!r}")
        raw_root = self.workflow_dir / workflow_id
        if raw_root.is_symlink():
            raise ValueError(f"molecular workflow directory is a symlink: {raw_root}")
        root = raw_root.resolve()
        if not root.is_relative_to(self.workflow_dir):
            raise ValueError(f"molecular workflow escapes workspace: {workflow_id!r}")
        root.mkdir(parents=True, exist_ok=True)
        return root

    def _workflow(self, manifest: UnifiedVaspManifest):
        workflow = cast(MolecularScientificSpec, manifest.scientific_spec).workflow
        path = workflow.molecule.structure_path
        if path is None:
            raise ValueError("molecular manifest requires a workspace-relative structure path")
        candidate = Path(path)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise ValueError("molecular manifest structure path must be workspace-relative without traversal")
        # Manifests intentionally persist workspace-relative snapshots.  The
        # existing molecular facade accepts a concrete local path, so resolve
        # it only at this internal adapter boundary after repository validation.
        workspace = cast(Workspace, self.workspace)
        try:
            resolved = resolve_workspace_relative_path(
                workspace, candidate, must_exist=True
            )
        except Exception as exc:
            raise ValueError(
                "molecular manifest structure path must be workspace-relative and contained"
            ) from exc
        return workflow.model_copy(update={
            "molecule": workflow.molecule.model_copy(update={"structure_path": resolved})
        })

    def _facade(self, manifest: UnifiedVaspManifest) -> MolecularVaspTools:
        return MolecularVaspTools(
            session=self.runtime.session,
            backend=self.runtime.backend,
            psp_dir=self.runtime.psp_dir,
            workflow_dir=self.workflow_dir_for(manifest),
            log_dir=self.runtime.log_dir,
            module_name=self.runtime.module_name,
            env_script=self.runtime.env_script,
            remote_psp_dir=self.runtime.remote_psp_dir,
            configured=self.runtime.configured,
        )

    @staticmethod
    def _operation(payload: dict, *, ok: bool | None = None) -> OperationResult:
        resolved_ok = payload.get("ok", True) if ok is None else ok
        return OperationResult(
            ok=bool(resolved_ok),
            data=payload,
            artifacts=list(payload.get("artifacts", [])),
            errors=list(payload.get("errors", [])),
            evidence_gaps=(
                [] if resolved_ok else list(payload.get("errors", []))
            ),
        )

    async def prepare(self, manifest: UnifiedVaspManifest) -> OperationResult:
        facade = self._facade(manifest)
        workflow_dir = self.workflow_dir_for(manifest)
        payload = await facade.prepare(
            self._workflow(manifest), output_dir=workflow_dir
        )
        return self._operation(payload)

    async def preflight(self, manifest: UnifiedVaspManifest) -> PreflightResult:
        facade = self._facade(manifest)
        payload = await facade.preflight(self._workflow(manifest))
        passed = bool(payload.get("ok", False))
        result = self._operation(payload, ok=passed)
        return PreflightResult(
            ok=result.ok,
            passed=passed,
            data=result.data,
            artifacts=result.artifacts,
            errors=result.errors,
            evidence_gaps=result.evidence_gaps,
        )

    async def submit(
        self,
        manifest: UnifiedVaspManifest,
        stage: UnifiedStage,
        resource: ResourceRequest,
    ) -> SubmissionResult:
        facade = self._facade(manifest)
        execution = stage.execution_fingerprint or manifest.execution_fingerprint
        if not execution:
            execution = execution_fingerprint(
                manifest.scientific_fingerprint, resource, stage,
                stage.attempt_inputs or None,
            )
        request_id = stage.request_id or derive_request_id(
            f"molecular:{manifest.workflow_id}", stage.name, execution
        )
        payload = await facade.submit(
            stage.name,
            self._workflow(manifest),
            resource=resource,
            request_id=request_id,
        )
        summary = payload.get("summary", {}) or {}
        errors = list(payload.get("errors", []))
        request_id = str(summary.get("request_id") or request_id)
        return SubmissionResult(
            ok=bool(payload.get("ok", False)),
            request_id=request_id,
            job_id=summary.get("job_id"),
            submitted=bool(payload.get("ok", False)),
            duplicate=bool(summary.get("already", False)),
            errors=errors,
            evidence_gaps=[] if payload.get("ok") else errors,
            data=summary,
        )

    async def status(self, manifest: UnifiedVaspManifest) -> StatusResult:
        facade = self._facade(manifest)
        stage_states: dict[str, str] = {}
        failed = False
        workflow = self._workflow(manifest)
        for stage in workflow.stages:
            payload = await facade.status(stage.name)
            summary = payload.get("summary", {}) or {}
            state = summary.get("state") or summary.get("stage") or "UNKNOWN"
            stage_states[stage.name.value] = str(state)
            if not payload.get("ok"):
                failed = True
        return StatusResult(
            ok=not failed,
            stage_states=stage_states,
            query_failed=failed,
        )

    async def reconcile(self, manifest: UnifiedVaspManifest) -> RecoveryResult:
        from photomatagent.scientific.applications.vasp.molecular.workflow import (
            load_task_state,
        )

        task_state = load_task_state(self.workflow_dir_for(manifest))
        if task_state is None:
            return RecoveryResult(ok=False, action="STOP", errors=["no task_state"])
        errors: list[str] = []
        workflow = self._workflow(manifest)
        for stage in workflow.stages:
            entry = task_state.stage_map().get(stage.name.value)
            if entry is None or not entry.request_id:
                continue
            outcome = await self.runtime.session.reconcile(entry.request_id)
            if outcome.outcome in {"FOUND_MULTIPLE", "FOUND_UNIQUE_UNKNOWN_STATE"}:
                errors.append(
                    f"{stage.name.value}: {outcome.error or outcome.outcome}"
                )
            elif outcome.error:
                errors.append(f"{stage.name.value}: {outcome.error}")
        return RecoveryResult(
            ok=not errors,
            action="AUTO_RESUME" if not errors else "RECONCILE",
            errors=errors,
        )

    async def collect(self, manifest: UnifiedVaspManifest) -> CollectionResult:
        facade = self._facade(manifest)
        evidence: list[ScientificEvidence] = []
        gaps: list[str] = []
        from photomatagent.scientific.applications.vasp.molecular.workflow import load_task_state
        task_state = load_task_state(self.workflow_dir_for(manifest))
        task_map = task_state.stage_map() if task_state is not None else {}
        stage_states: dict[str, str] = {}
        workflow = self._workflow(manifest)
        # WorkflowSpec is the source of truth for completion.  Analysis
        # stages are reports over computational outputs; every energy stage
        # declared by the workflow is required for validated collection.
        energy_stages = {
            StageName.RELAX,
            StageName.STATIC,
            StageName.CORRECTED_STATIC,
            StageName.STATIC_PRECONVERGE,
            StageName.STATIC_HSE,
        }
        required = [stage for stage in workflow.stages if stage.name in energy_stages]
        for stage in workflow.stages:
            if stage not in required:
                continue
            existing = task_map.get(stage.name.value)
            if existing is None:
                gaps.append(f"required stage {stage.name.value} has not run")
                stage_states[stage.name.value] = "PLANNED"
                continue
            if existing.state == "VALIDATED":
                found = self._evidence_from_payload(
                    self.workflow_dir_for(manifest), stage.name.value
                )
                if found:
                    evidence.extend(found)
                    stage_states[stage.name.value] = "VALIDATED"
                else:
                    gaps.append(f"required stage {stage.name.value} has no typed evidence")
                    stage_states[stage.name.value] = "VALIDATION_FAILED"
                continue
            if existing.state not in {"COMPLETED", "COLLECTED"}:
                gaps.append(
                    f"required stage {stage.name.value} is {existing.state}, not validated"
                )
                stage_states[stage.name.value] = str(existing.state)
                continue
            payload = await facade.collect(stage.name)
            found = self._evidence_from_payload(
                self.workflow_dir_for(manifest), stage.name.value
            )
            if payload.get("ok") and bool((payload.get("summary") or {}).get("validated")) and found:
                evidence.extend(found)
                stage_states[stage.name.value] = str(
                    (payload.get("summary") or {}).get("state") or "VALIDATED"
                )
            else:
                if payload.get("errors"):
                    gaps.extend(str(item) for item in payload.get("errors", []))
                if not found:
                    gaps.append(f"required stage {stage.name.value} has no typed evidence")
                elif not payload.get("ok") or not bool((payload.get("summary") or {}).get("validated")):
                    gaps.append(f"required stage {stage.name.value} is not validated")
                stage_states[stage.name.value] = "VALIDATION_FAILED"
        validated = bool(required) and len(stage_states) == len(required) and not gaps
        return CollectionResult(
            ok=not gaps,
            validated=validated,
            evidence=evidence,
            evidence_gaps=gaps or ([] if validated else ["one or more molecular stages are not validated"]),
            stage_states=stage_states,
        )

    def _evidence_from_payload(self, root: Path, stage: str) -> list[ScientificEvidence]:
        # The molecular collector's full ScientificEvidence list is persisted
        # in evidence.json; the unified tool pack will load it for the final
        # ToolResult. Here we avoid duplicating evidence construction.
        path = root / "results" / stage / "evidence.json"
        if not path.is_file():
            return []
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
            return [ScientificEvidence.model_validate(item) for item in payload]
        except (OSError, ValueError, TypeError):
            return []

    async def report(
        self, manifest: UnifiedVaspManifest, request: ReportRequest
    ) -> ReportResult:
        facade = self._facade(manifest)
        workflow = self._workflow(manifest)
        workflow_dir = self.workflow_dir_for(manifest)
        if request.kind.value == "orbitals":
            result_dir = workflow_dir / "results" / "orbital_homo"
            payload = await facade.analyze_orbitals(
                result_dir,
                charge=workflow.molecule.total_charge,
                spin_multiplicity=workflow.molecule.spin_multiplicity,
                box_ang=workflow.molecule.box_ang,
            )
        elif request.kind.value == "esp":
            result_dir = workflow_dir / "results" / "esp"
            payload = await facade.analyze_esp(result_dir)
        elif request.kind.value == "binding_energy":
            if not request.related_workflow_ids:
                return ReportResult(
                    ok=False,
                    report_kind=request.kind,
                    errors=[
                        "binding_energy requires explicit related_workflow_ids; "
                        "no fragment references were fabricated"
                    ],
                    evidence_gaps=["complete binding reference set is missing"],
                )
            try:
                references = [
                    self._binding_reference(workflow_dir, related_id)
                    for related_id in request.related_workflow_ids
                ]
            except (OSError, ValueError, KeyError) as exc:
                return ReportResult(
                    ok=False,
                    report_kind=request.kind,
                    errors=[f"invalid binding reference: {exc}"],
                    evidence_gaps=["binding reference could not be resolved"],
                )
            from photomatagent.scientific.applications.vasp.molecular.binding import (
                BindingEnergyInput,
            )

            complex_dir = self._energy_results_dir(workflow_dir)
            payload = await facade.binding_energy(
                BindingEnergyInput(
                    complex_name=workflow.molecule.name,
                    complex_dir=str(complex_dir),
                    references=references,
                    charge=workflow.molecule.total_charge,
                )
            )
        else:
            payload = {"ok": True, "summary": {"kind": request.kind.value}}
        return ReportResult(
            ok=bool(payload.get("ok", True)),
            report_kind=request.kind,
            data=payload,
            errors=list(payload.get("errors", [])),
            evidence_gaps=list(payload.get("errors", [])) if not payload.get("ok", True) else [],
        )

    @staticmethod
    def _energy_results_dir(root: Path) -> Path:
        for stage in ("corrected_static", "static", "relax"):
            candidate = root / "results" / stage
            if (candidate / "results.json").is_file():
                return candidate
        # Keep the path deterministic; binding's typed parser reports the
        # missing result as a bounded error rather than inventing energy data.
        return root / "results" / "relax"

    def _binding_reference(self, complex_root: Path, workflow_id: str) -> BindingReference:
        related = Path(workflow_id)
        if related.is_absolute() or related.name != workflow_id or ".." in related.parts:
            raise ValueError(f"workflow id is not a safe child id: {workflow_id!r}")
        root = (complex_root.parent / workflow_id).resolve()
        if not root.is_relative_to(self.workflow_dir):
            raise ValueError(f"workflow id escapes molecular workspace: {workflow_id!r}")
        manifest = root / "workflow.json"
        if not manifest.is_file():
            raise FileNotFoundError(f"workflow.json missing for {workflow_id}")
        workflow = WorkflowSpec.model_validate_json(manifest.read_text(encoding="utf-8"))
        result_dir = self._energy_results_dir(root)
        return BindingReference(
            name=workflow.molecule.name,
            results_dir=str(result_dir),
            charge=workflow.molecule.total_charge,
            role="ion" if workflow.molecule.total_charge else "fragment",
        )
