"""Workspace-contained atomic manifest persistence for unified VASP workflows."""

from __future__ import annotations

import hashlib
import io
import json
import os
import re
import stat
import uuid
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator, cast

from pydantic import ValidationError

from photomatagent.errors import ToolExecutionError
from photomatagent.scientific.applications.vasp.unified.fingerprints import (
    scientific_fingerprint,
)
from photomatagent.scientific.applications.vasp.unified.models import (
    MolecularScientificSpec,
    PeriodicScientificSpec,
    ScientificSpec,
    StudyScientificSpec,
    UnifiedVaspManifest,
    UnifiedVaspRequest,
    VaspWorkflowKind,
    WorkflowState,
)
from photomatagent.scientific.applications.vasp.molecular.models import StructureKind
from photomatagent.workspace import Workspace

MANIFEST_NAME = "manifest.json"
SNAPSHOT_MANIFEST_NAME = "snapshot.json"
SUPPORTED_LEGACY_SCHEMA_VERSIONS = {"1.0", ""}
SUPPORTED_SCHEMA_VERSION = "2.0"
WORKFLOW_ID_PATTERN = re.compile(r"vasp_[0-9a-f]{16}\Z")
MANAGED_VASP_PREFIX = (".photomatagent", "vasp")


class ManifestConflictError(RuntimeError):
    """Raised when saving with a stale expected revision."""


def validate_workflow_id(workflow_id: str) -> str:
    """Reject any workflow identity not generated by this repository."""
    if not isinstance(workflow_id, str) or WORKFLOW_ID_PATTERN.fullmatch(workflow_id) is None:
        raise ToolExecutionError(f"invalid VASP workflow ID: {workflow_id!r}")
    return workflow_id


def resolve_workspace_relative_path(
    workspace: Workspace, path: str | Path, *, must_exist: bool
) -> Path:
    """Resolve a public workspace-relative reference without normalization."""
    candidate = Path(path)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise ToolExecutionError(
            f"path must be workspace-relative without traversal: {path}"
        )
    return workspace.resolve(str(candidate), must_exist=must_exist)


def managed_vasp_path(workspace: Workspace, *parts: str) -> Path:
    """Return a managed VASP path after checking its static components."""
    path = workspace.root.joinpath(*MANAGED_VASP_PREFIX, *parts)
    revalidate_managed_vasp_path(workspace, path)
    return path


def revalidate_managed_vasp_path(workspace: Workspace, path: Path) -> None:
    """Reject a managed path containing a symlinked component."""
    try:
        relative = path.relative_to(workspace.root)
    except ValueError as exc:
        raise ToolExecutionError(f"managed VASP path is outside workspace: {path}") from exc
    if relative.parts[: len(MANAGED_VASP_PREFIX)] != MANAGED_VASP_PREFIX:
        raise ToolExecutionError(f"path is outside managed VASP storage: {path}")
    cursor = workspace.root
    for part in relative.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            raise ToolExecutionError(f"managed VASP path contains a symlink: {cursor}")
    workspace.resolve(relative.as_posix(), must_exist=False)


class ManifestRepository:
    def __init__(self, workspace: Workspace) -> None:
        self.workspace = workspace

    # -- path helpers -------------------------------------------------------

    def workflow_dir(self, workflow_id: str) -> Path:
        """Return (and create) the managed directory for one workflow."""
        directory = self._workflow_path(workflow_id)
        self._mkdir_managed(directory)
        return directory

    def _manifest_path(self, workflow_id: str) -> Path:
        return self._workflow_child_path(workflow_id, MANIFEST_NAME)

    def _workflow_path(self, workflow_id: str) -> Path:
        workflow_id = validate_workflow_id(workflow_id)
        return self._managed_path("workflows", workflow_id)

    def _workflow_child_path(self, workflow_id: str, *parts: str) -> Path:
        workflow_id = validate_workflow_id(workflow_id)
        return self._managed_path("workflows", workflow_id, *parts)

    def _managed_path(self, *parts: str) -> Path:
        return managed_vasp_path(self.workspace, *parts)

    def _revalidate_managed_path(self, path: Path) -> None:
        """Reject static symlinks before a managed path is created or written.

        This is a containment check around each local filesystem operation; it
        cannot turn host filesystem operations into an OS sandbox.
        """
        revalidate_managed_vasp_path(self.workspace, path)

    def _mkdir_managed(self, directory: Path) -> None:
        with self._managed_directory_fd(directory, create=True):
            pass
        self._revalidate_managed_path(directory)

    @contextmanager
    def _managed_directory_fd(
        self, directory: Path, *, create: bool
    ) -> Iterator[int]:
        """Open a managed directory without following component symlinks.

        On POSIX with `O_NOFOLLOW`, this uses descriptor-relative operations,
        so a component swap after validation cannot redirect a managed write.
        On a platform without that flag, static and pre-operation symlinks are
        still rejected, but concurrent replacement is not fully preventable.
        """
        self._revalidate_managed_path(directory)
        try:
            relative = directory.relative_to(self.workspace.root)
            root_flags = (
                os.O_RDONLY
                | getattr(os, "O_DIRECTORY", 0)
                | getattr(os, "O_NOFOLLOW", 0)
            )
            current_fd = os.open(self.workspace.root, root_flags)
            child_flags = root_flags | getattr(os, "O_NOFOLLOW", 0)
            try:
                for part in relative.parts:
                    try:
                        child_fd = os.open(part, child_flags, dir_fd=current_fd)
                    except FileNotFoundError:
                        if not create:
                            raise
                        try:
                            os.mkdir(part, 0o700, dir_fd=current_fd)
                        except FileExistsError:
                            pass
                        child_fd = os.open(part, child_flags, dir_fd=current_fd)
                    os.close(current_fd)
                    current_fd = child_fd
                yield current_fd
            finally:
                os.close(current_fd)
        except (NotImplementedError, OSError, TypeError) as exc:
            raise ToolExecutionError(
                f"managed VASP directory cannot be opened safely: {directory}"
            ) from exc

    def _resolve_source(self, path: str | Path) -> Path:
        try:
            return resolve_workspace_relative_path(
                self.workspace, path, must_exist=True
            )
        except ToolExecutionError as exc:
            raise ToolExecutionError(
                "VASP manifest source path must be workspace-relative, "
                f"non-traversing, and present in workspace: {path}"
            ) from exc

    # -- create -------------------------------------------------------------

    def create(self, request: UnifiedVaspRequest) -> UnifiedVaspManifest:
        """Create a new manifest and snapshot referenced source inputs."""
        workflow_id = f"vasp_{uuid.uuid4().hex[:16]}"
        workflow = self.workflow_dir(workflow_id)
        source_dir = self._workflow_child_path(workflow_id, "source")
        self._mkdir_managed(source_dir)

        spec = self._snapshot_sources(request.scientific_spec, source_dir, workflow_id)
        manifest = UnifiedVaspManifest(
            workflow_id=workflow_id,
            workflow_kind=request.workflow_kind,
            scientific_spec=spec,
            # Snapshot paths and bytes are the immutable scientific input.
            # Hash the persisted snapshot, never the caller's mutable source
            # reference, so current-schema load verification is stable.
            scientific_fingerprint=scientific_fingerprint(spec),
            stages=[],
        )
        self._write_atomic(self._manifest_path(workflow_id), manifest)
        self._write_snapshot_manifest(workflow)
        return manifest

    def _snapshot_sources(
        self, spec: ScientificSpec, source_dir: Path, workflow_id: str
    ) -> ScientificSpec:
        """Copy referenced structure files into the workflow snapshot."""
        kind = spec.kind
        if kind == "periodic":
            periodic = cast(PeriodicScientificSpec, spec)
            source = self._resolve_source(periodic.structure_path)
            snapshot = self._snapshot_file(source, source_dir, "structure")
            self._record_snapshot_source(
                workflow_id, source, snapshot
            )
            return periodic.model_copy(
                update={"structure_path": self.workspace.relative(snapshot)}
            )
        if kind == "molecular":
            molecular = cast(MolecularScientificSpec, spec)
            path = molecular.workflow.molecule.structure_path
            if path is None:
                raise ToolExecutionError(
                    "molecular unified manifest requires a structure_path"
                )
            source = self._resolve_source(path)
            snapshot = self._snapshot_file(source, source_dir, "molecule_structure")
            molecule_update: dict[str, Any] = {
                "structure_path": self.workspace.relative(snapshot)
            }
            if molecular.workflow.molecule.structure_kind is None and snapshot.suffix.lower() == ".xyz":
                # JSON revalidation infers XYZ from the persisted suffix. Make
                # that normalization explicit before hashing the snapshot.
                molecule_update["structure_kind"] = StructureKind.XYZ
            molecule = molecular.workflow.molecule.model_copy(
                update=molecule_update
            )
            workflow = molecular.workflow.model_copy(update={"molecule": molecule})
            self._record_snapshot_source(workflow_id, source, snapshot)
            return molecular.model_copy(update={"workflow": workflow})
        if kind == "study":
            study = cast(StudyScientificSpec, spec)
            systems = []
            for system in study.request.systems:
                if system.structure_path is None:
                    systems.append(system)
                    continue
                source = self._resolve_source(system.structure_path)
                snapshot = self._snapshot_file(
                    source, source_dir, f"study_{system.system_id}"
                )
                systems.append(
                    system.model_copy(update={"structure_path": self.workspace.relative(snapshot)})
                )
                self._record_snapshot_source(workflow_id, source, snapshot)
            request = study.request.model_copy(update={"systems": systems})
            return study.model_copy(update={"request": request})
        return spec

    def _snapshot_file(
        self, source: Path, source_dir: Path, stem: str
    ) -> Path:
        self._revalidate_managed_path(source_dir)
        suffix = source.suffix or ".dat"
        target = source_dir / f"{stem}{suffix}"
        self._revalidate_managed_path(target)
        if target.exists():
            target = source_dir / f"{stem}-{uuid.uuid4().hex[:8]}{suffix}"
            self._revalidate_managed_path(target)
        with source.open("rb") as handle:
            self._write_stream_atomically(target, handle)
        return target

    def _record_snapshot_source(
        self, workflow_id: str, original: Path, snapshot: Path
    ) -> None:
        data = self._load_snapshot_manifest(workflow_id)
        data["files"].append(
            {
                "original": self.workspace.relative(original),
                "snapshot": self.workspace.relative(snapshot),
                "sha256": _sha256_file(snapshot),
            }
        )
        self._write_json_atomic(
            self._workflow_child_path(workflow_id, SNAPSHOT_MANIFEST_NAME), data
        )

    def _load_snapshot_manifest(self, workflow_id: str) -> dict[str, Any]:
        path = self._workflow_child_path(workflow_id, SNAPSHOT_MANIFEST_NAME)
        if not path.exists():
            return {"workflow_id": workflow_id, "files": []}
        return json.loads(path.read_text(encoding="utf-8"))

    def _write_snapshot_manifest(self, workflow: Path) -> None:
        # Snapshot manifest already exists if sources were recorded above.
        path = workflow / SNAPSHOT_MANIFEST_NAME
        if not path.exists():
            self._write_json_atomic(
                path,
                {
                    "workflow_id": workflow.name,
                    "files": [],
                },
            )

    # -- load ---------------------------------------------------------------

    def load(self, workflow_id: str) -> UnifiedVaspManifest:
        """Load a versioned manifest; unknown versions are not reinterpreted."""
        path = self._manifest_path(workflow_id)
        if not path.exists():
            raise KeyError(f"unknown workflow: {workflow_id}")
        raw = json.loads(path.read_text(encoding="utf-8"))
        schema_version = raw.get("schema_version")
        migrated_legacy = False
        if schema_version == SUPPORTED_SCHEMA_VERSION:
            try:
                manifest = UnifiedVaspManifest.model_validate(raw)
            except ValidationError as exc:
                raise ValueError(f"invalid unified VASP manifest: {exc}") from exc
        elif schema_version in SUPPORTED_LEGACY_SCHEMA_VERSIONS or schema_version is None:
            migrated = self._migrate_legacy(raw, workflow_id)
            migrated = self._migrate_legacy_sources(migrated, workflow_id)
            manifest = UnifiedVaspManifest.model_validate(migrated)
            migrated_legacy = True
        else:
            raise ValueError(
                f"unsupported VASP manifest schema_version {schema_version!r}"
            )
        if manifest.workflow_id != workflow_id:
            raise ValueError("manifest workflow_id does not match its storage path")
        validate_workflow_id(manifest.workflow_id)
        self._validate_loaded_paths(manifest)
        recomputed_scientific = scientific_fingerprint(manifest)
        if manifest.scientific_fingerprint != recomputed_scientific:
            raise ValueError("manifest scientific fingerprint does not match immutable snapshot/spec")
        if migrated_legacy:
            # Commit the explicit, reset migration atomically without giving
            # legacy execution metadata a second chance to become authority.
            self._write_atomic(path, manifest)
        return manifest

    def _validate_loaded_paths(self, manifest: UnifiedVaspManifest) -> None:
        """Validate every persisted snapshot and its immutable inventory."""
        expected: list[str] = []
        spec = manifest.scientific_spec
        if manifest.workflow_kind is VaspWorkflowKind.PERIODIC:
            expected = [cast(PeriodicScientificSpec, spec).structure_path]
        elif manifest.workflow_kind is VaspWorkflowKind.MOLECULAR:
            path = cast(MolecularScientificSpec, spec).workflow.molecule.structure_path
            if path is None:
                raise ToolExecutionError("molecular structure path is required in unified manifests")
            expected = [str(path)]
        elif manifest.workflow_kind is VaspWorkflowKind.STUDY:
            expected = [
                str(system.structure_path)
                for system in cast(StudyScientificSpec, spec).request.systems
                if system.structure_path is not None
            ]
        inventory = self._load_snapshot_manifest(manifest.workflow_id)
        files = inventory.get("files")
        if inventory.get("workflow_id") != manifest.workflow_id or not isinstance(files, list):
            raise ValueError("invalid immutable snapshot inventory")
        records: dict[str, str] = {}
        for item in files:
            if not isinstance(item, dict):
                raise ValueError("invalid immutable snapshot inventory entry")
            snapshot = item.get("snapshot")
            digest = item.get("sha256")
            if not isinstance(snapshot, str) or not isinstance(digest, str):
                raise ValueError("invalid immutable snapshot inventory entry")
            if snapshot in records or len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest.lower()):
                raise ValueError("invalid immutable snapshot inventory entry")
            path = self._verified_snapshot_path(manifest.workflow_id, snapshot)
            if _sha256_file(path) != digest:
                raise ValueError("snapshot bytes do not match immutable inventory")
            records[snapshot] = digest
        for reference in expected:
            try:
                self._verified_snapshot_path(manifest.workflow_id, reference)
            except ToolExecutionError as exc:
                if manifest.workflow_kind is VaspWorkflowKind.MOLECULAR:
                    raise ToolExecutionError(
                        "molecular structure path must be workspace-relative, contained, and present"
                    ) from exc
                raise
            if reference not in records:
                raise ValueError("manifest snapshot is absent from immutable inventory")

    def _verified_snapshot_path(self, workflow_id: str, reference: str) -> Path:
        """Resolve one persisted snapshot below its workflow source directory."""
        candidate = Path(reference)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise ToolExecutionError("persisted snapshot path must be relative and non-traversing")
        root = self._workflow_child_path(workflow_id, "source")
        path = self.workspace.resolve(reference, must_exist=True)
        try:
            path.relative_to(root)
        except ValueError as exc:
            raise ToolExecutionError("persisted snapshot is outside workflow source") from exc
        cursor = self.workspace.root
        for part in candidate.parts:
            cursor /= part
            if cursor.is_symlink():
                raise ToolExecutionError("persisted snapshot path contains a symlink")
        return path

    def _migrate_legacy_sources(
        self, raw: dict[str, Any], workflow_id: str
    ) -> dict[str, Any]:
        """Snapshot old workspace sources before granting current-schema use."""
        candidate = UnifiedVaspManifest.model_validate(raw)
        source_dir = self._workflow_child_path(workflow_id, "source")
        self._mkdir_managed(source_dir)
        spec = self._snapshot_sources(candidate.scientific_spec, source_dir, workflow_id)
        updated = dict(raw)
        updated["scientific_spec"] = spec.model_dump(mode="json")
        provisional = UnifiedVaspManifest.model_validate(
            {**updated, "scientific_fingerprint": "legacy-migration-pending"}
        )
        updated["scientific_fingerprint"] = scientific_fingerprint(provisional)
        self._write_snapshot_manifest(self._workflow_path(workflow_id))
        return updated

    def resolve_workspace_artifact(self, reference: str) -> Path:
        """Resolve a restart artifact without accepting links or escapes."""
        candidate = Path(reference)
        if candidate.is_absolute() or ".." in candidate.parts or not candidate.parts:
            raise ToolExecutionError("restart artifact path must be workspace-relative and non-traversing")
        path = self.workspace.resolve(str(candidate), must_exist=True)
        cursor = self.workspace.root
        for part in candidate.parts:
            cursor /= part
            if cursor.is_symlink():
                raise ToolExecutionError("restart artifact path contains a symlink")
        if not path.is_file():
            raise ToolExecutionError("restart artifact must be a regular file")
        return path

    @staticmethod
    def _migrate_legacy(raw: dict[str, Any], workflow_id: str) -> dict[str, Any]:
        """Explicitly migrate an unversioned/legacy manifest to schema 2.0.

        Only a minimal known legacy shape is accepted. Anything else is
        rejected instead of silently guessed.
        """
        if "workflow_kind" not in raw or "scientific_spec" not in raw:
            raise ValueError(
                "unsupported legacy VASP manifest: missing workflow_kind or "
                "scientific_spec; automatic migration is not attempted"
            )
        migrated = dict(raw)
        migrated["schema_version"] = SUPPORTED_SCHEMA_VERSION
        migrated["workflow_id"] = raw.get("workflow_id") or workflow_id
        migrated["revision"] = 0
        migrated["state"] = WorkflowState.PLANNED.value
        # Legacy runtime authority cannot be safely reconstructed.  Clear all
        # privileged execution state and require an explicit current-schema
        # plan/preflight/approval flow after source snapshotting.
        migrated["stages"] = []
        migrated["events"] = []
        migrated["child_workflow_ids"] = {}
        migrated["study_task_states"] = {}
        migrated["study_stage_states"] = {}
        migrated["resource_budget_consumed_core_hours"] = 0.0
        migrated["resource_budget_submitted_jobs"] = 0
        migrated["decision_epoch"] = 0
        # A legacy fingerprint had no current-schema verification contract.
        # Recompute it during this explicit migration; do not trust it later.
        migrated.pop("scientific_fingerprint", None)
        provisional = dict(migrated)
        provisional["scientific_fingerprint"] = "legacy-migration-pending"
        candidate = UnifiedVaspManifest.model_validate(provisional)
        migrated["scientific_fingerprint"] = scientific_fingerprint(candidate)
        migrated["execution_fingerprint"] = None
        return migrated

    # -- save ---------------------------------------------------------------

    def save(
        self, manifest: UnifiedVaspManifest, expected_revision: int
    ) -> UnifiedVaspManifest:
        """Atomically write a new manifest revision.

        The stored manifest must currently be at ``expected_revision``;
        otherwise a stale write is rejected.
        """
        path = self._manifest_path(manifest.workflow_id)
        current = self.load(manifest.workflow_id) if path.exists() else None
        current_revision = current.revision if current is not None else 0
        if current_revision != expected_revision:
            raise ManifestConflictError(
                f"stale manifest write for {manifest.workflow_id}: stored "
                f"revision={current_revision}, expected={expected_revision}"
            )
        updated = manifest.model_copy(update={"revision": expected_revision + 1})
        self._write_atomic(path, updated)
        return updated

    # -- persistence helpers -------------------------------------------------

    def _write_atomic(
        self, path: Path, manifest: UnifiedVaspManifest
    ) -> None:
        self._write_json_atomic(path, manifest.model_dump(mode="json"))

    def _write_json_atomic(self, path: Path, payload: Any) -> None:
        text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        self._write_stream_atomically(path, io.BytesIO(text.encode("utf-8")))

    def write_derived_json(self, relative_path: str | Path, payload: Any) -> Path:
        """Atomically write a workspace-contained derived artifact.

        Derived artifacts (such as the compatibility study-state view) are not
        manifests, but must receive the same descriptor-relative, no-follow
        write discipline.  Callers may only name a workspace-relative path.
        """
        relative = Path(relative_path)
        if relative.is_absolute() or ".." in relative.parts or not relative.parts:
            raise ToolExecutionError(
                f"derived VASP artifact must be workspace-relative: {relative_path}"
            )
        target = self.workspace.root.joinpath(relative)
        self._write_workspace_json_atomic(target, payload)
        return target

    def _write_stream_atomically(self, path: Path, source: Any) -> None:
        """Write a managed file through a no-follow parent directory FD."""
        self._revalidate_managed_path(path)
        with self._managed_directory_fd(path.parent, create=True) as directory_fd:
            self._write_stream_in_directory(directory_fd, path.name, source)
        self._revalidate_managed_path(path)

    def _write_workspace_json_atomic(self, path: Path, payload: Any) -> None:
        relative = path.relative_to(self.workspace.root)
        self._validate_workspace_artifact_path(path)
        text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        with self._workspace_directory_fd(path.parent, create=True) as directory_fd:
            self._write_stream_in_directory(
                directory_fd, path.name, io.BytesIO(text.encode("utf-8"))
            )
        self._validate_workspace_artifact_path(self.workspace.root.joinpath(relative))

    def _validate_workspace_artifact_path(self, path: Path) -> None:
        try:
            relative = path.relative_to(self.workspace.root)
        except ValueError as exc:
            raise ToolExecutionError(f"derived VASP artifact is outside workspace: {path}") from exc
        cursor = self.workspace.root
        for part in relative.parts:
            cursor = cursor / part
            if cursor.is_symlink():
                raise ToolExecutionError(f"derived VASP artifact contains a symlink: {cursor}")

    @contextmanager
    def _workspace_directory_fd(self, directory: Path, *, create: bool) -> Iterator[int]:
        self._validate_workspace_artifact_path(directory)
        try:
            relative = directory.relative_to(self.workspace.root)
            flags = (
                os.O_RDONLY
                | getattr(os, "O_DIRECTORY", 0)
                | getattr(os, "O_NOFOLLOW", 0)
            )
            current_fd = os.open(self.workspace.root, flags)
            try:
                for part in relative.parts:
                    try:
                        child_fd = os.open(part, flags, dir_fd=current_fd)
                    except FileNotFoundError:
                        if not create:
                            raise
                        os.mkdir(part, 0o700, dir_fd=current_fd)
                        child_fd = os.open(part, flags, dir_fd=current_fd)
                    os.close(current_fd)
                    current_fd = child_fd
                yield current_fd
            finally:
                os.close(current_fd)
        except (NotImplementedError, OSError, TypeError) as exc:
            raise ToolExecutionError(
                f"derived VASP artifact directory cannot be opened safely: {directory}"
            ) from exc

    @staticmethod
    def _write_stream_in_directory(directory_fd: int, name: str, source: Any) -> None:
        try:
            existing = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        except FileNotFoundError:
            existing = None
        if existing is not None and stat.S_ISLNK(existing.st_mode):
            raise ToolExecutionError(f"refusing to replace symlinked VASP artifact: {name}")
        temporary_name = f".{name}.tmp.{uuid.uuid4().hex[:8]}"
        temporary_fd: int | None = None
        try:
            temporary_fd = os.open(
                temporary_name,
                os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
                0o600,
                dir_fd=directory_fd,
            )
            with os.fdopen(temporary_fd, "wb") as handle:
                temporary_fd = None
                while chunk := source.read(65536):
                    handle.write(chunk)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_name, name, src_dir_fd=directory_fd, dst_dir_fd=directory_fd)
            os.fsync(directory_fd)
        except Exception:
            if temporary_fd is not None:
                os.close(temporary_fd)
            try:
                os.unlink(temporary_name, dir_fd=directory_fd)
            except FileNotFoundError:
                pass
            raise


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def ensure_managed_vasp_directory(workspace: Workspace, directory: Path) -> None:
    """Create a managed VASP directory with the repository's FD safety gate."""
    ManifestRepository(workspace)._mkdir_managed(directory)
